find_package(Doxygen)
if (DOXYGEN_FOUND)
    set(DOXYGEN_ALWAYS_DETAILED_SEC YES)
    set(DOXYGEN_JAVADOC_AUTOBRIEF YES)
    set(DOXYGEN_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/docs)
    set(DOXYGEN_USE_MDFILE_AS_MAINPAGE ${CMAKE_SOURCE_DIR}/README.md)
    doxygen_add_docs(RingBufferDoc
        ${CMAKE_SOURCE_DIR}/README.md
        ${CMAKE_SOURCE_DIR}/lib
        ALL
    )
endif(DOXYGEN_FOUND)
